### ISSUE TITLE
Path Error | Cannot ingest

### ISSUE THREAD

**Issue by atxcowboy** [su77ungr/CASALIOY#1]
When I try to ingest, I get:
```
python ingest.py source_documents/dsgvo.txt
Traceback (most recent call last):
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\langchain\embeddings\llamacpp.py", line 76, in validate_environment
    from llama_cpp import Llama
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\llama_cpp\llama_cpp.py", line 11, in <module>
    (_lib_path,) = chain(
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ai\CASALIOY\ingest.py", line 26, in <module>
    main()
  File "E:\ai\CASALIOY\ingest.py", line 15, in main
    llama = LlamaCppEmbeddings(model_path="./models/ggml-model-q4_0.bin")
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Users\Sasch\.conda\envs\casalioy\lib\site-packages\langchain\embeddings\llamacpp.py", line 98, in validate_environment
    raise NameError(f"Could not load Llama model from path: {model_path}")
NameError: Could not load Llama model from path: ./models/ggml-model-q4_0.bin
```

The models are there though:
```
(casalioy) E:\ai\CASALIOY>ls -la models
total 7810528
drwxr-xr-x 1 Sasch 197609          0 May 10 11:36 .
drwxr-xr-x 1 Sasch 197609          0 May 10 12:54 ..
-rw-r--r-- 1 Sasch 197609 3785248281 May 10 11:31 ggml-gpt4all-j-v1.3-groovy.bin
-rw-r--r-- 1 Sasch 197609 4212727017 May 10 11:32 ggml-model-q4_0.bin
```

**Comment by su77ungr** [comment]
I could recreate this error by using a deprecated file path. 

So try to use an absolute path instead. 

>  FULL-PATH/models/ggml-model-q4_0.bin

**Comment by su77ungr** [comment]
Also. Make sure you have installed and put your binaries inside models

 GPT4ALL: [ggml-gpt4all-j-v1.3-groovy.bin](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin) 

Embedding: [ggml-model-q4_0.bin](https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin)

**Comment by atxcowboy** [comment]
Thank you for double checking! I have that setup, but I noticed a difference in the versions of llama-cpp-python between privateGPT and your fork. PrivateGPT uses llama-cpp-python v0.1.47 and you're using v0.1.14.
I can ingest with privateGPT and when I change the version in that conda environment, I get the same error as mentioned earlier. 

The model can be found:
 E:\ai\CASALIOY>python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print(os.path.exists('./models/ggml-model-q4_0.bin'))
True

When I change the version in your environment to v0.1.47 I can ingest.

**Comment by su77ungr** [comment]
Thank your for the notice. That's what i was thinking about too. I changed the requirements file a few hours ago but forgot to notice you.

Updated main branch 
Also increased the speed of qdrant so just git pull. 

Cheers.
