### ISSUE TITLE
DOC: Model link is wrong for "GPT4All-13b-snoozy q5" at readme file

### ISSUE THREAD

**Issue by madeepakkumar1** [su77ungr/CASALIOY#106]
### Issue with current documentation:

Model link is wrong for "GPT4All-13b-snoozy q5" at readme file

**Comment by su77ungr** [comment]
open a PR with the right one :)

**Comment by su77ungr** [comment]
thanks for the notice. we might want to upgrade non v3 models and add a banner older models might break due to llamacpp. 

did you check other models too?

**Comment by madeepakkumar1** [comment]
There is one more where backend link is not there

Title in readme file: Models inside of the GPT-J ecosphere
model: GPT4All-J 6B v1.0

**Comment by su77ungr** [comment]
with https://github.com/su77ungr/CASALIOY/commit/ed1afb323a9dad55730f37402d86b8b91fa32d91
