### ISSUE TITLE
gpt_tokenize: unknown token

### ISSUE THREAD

**Issue by hippalectryon-0** [su77ungr/CASALIOY#13]
Related: https://github.com/imartinez/privateGPT/issues/13

I thought this version was supposed to solve (or suppress) this warning, but I still get `gpt_tokenize: unknown token 'ú'` when running the basic README example (install requirements, ingest default content, start default).

**Comment by su77ungr** [comment]
This is due to a different formatting of the state_of_the_union.txt I purposely kept the same to uphold benchmarks. 

I consider this a non-critical issue as well because this is likely caused by whitespace or unsupported characters. You can change the encoding type in the TextParser.

**Comment by hippalectryon-0** [comment]
> This is due to a different formatting of the state_of_the_union.txt I purposely kept the same to uphold benchmarks.
Even removing state_of_the_union.txt and recreating the db, I get the same warnings.

**Comment by su77ungr** [comment]
That's interrsting. Does it impact performance? Can it still ingest your data?

**Comment by hippalectryon-0** [comment]
The ingestion script runs fine (but it already did fine before I removed the sotu.txt; the warnings only appear durring `python startLLM.py` after submitting a question).

I haven't managed to get startLLM to work properly yet, but I don't know how related to this issue this is. Using the default .env, after outputting the warnings, the script seemingly hangs forever. If I load the ggjt embedding instead of the default one, I get `ggml_new_tensor_impl: not enough space in the context's memory pool (needed 16891327760, available 16770413008)` regardless of the value of `MODEL_N_CTX`. Haven't tried with LlamaCpp  yet.

**Comment by hippalectryon-0** [comment]
Not happening anymore
