### ISSUE TITLE
No module named 'dotenv when ingest.py

### ISSUE THREAD

**Issue by hisxo** [su77ungr/CASALIOY#18]
Hello,

Starting from scratch, error when `python3 ingest.py source_documents/`

```
root@scw-boring-herschel:~/CASALIOY# python3 ingest.py source_documents/
Traceback (most recent call last):
  File "/root/CASALIOY/ingest.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

You should update the file `requirements.txt`.

Regards

**Comment by su77ungr** [comment]
try pip install python-dotenv. jap

**Comment by hisxo** [comment]
Yes it's fine now, but maybe useful to add it on `requirements.txt` ? :)

Cheers

**Comment by su77ungr** [comment]
This should be a native module. May cause errors when running python3. Added nonetheless.
