### ISSUE TITLE
Any way to use this with any custom model, outside the gpt4all ecosystem?

### ISSUE THREAD

**Issue by Curiosity007** [su77ungr/CASALIOY#2]
If yes, can you please document the process of creating compatible model files, and incorporate in the codebase?

**Comment by su77ungr** [comment]
This is dependent on the implementation of GPT4ALL inside Langchain. But we should be able to use another loader. I'm currently on that.

**Comment by su77ungr** [comment]
Use native LlamaCpp instead of GPT4ALL
