### ISSUE TITLE
exception: integer divide by zero while using gui

### ISSUE THREAD

**Issue by hippalectryon-0** [su77ungr/CASALIOY#27]
Full log [here](https://pastebin.com/3dw9Rytw)

Context: used the gui, first prompt went through fine, second prompt gave this error:

```
\CASALIOY\venv\Lib\site-packages\llama_cpp\llama_cpp.py", line 335, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: integer divide by zero
```

**Comment by alxspiker** [comment]
Checking this out right now

**Comment by alxspiker** [comment]
> Full log [here](https://pastebin.com/3dw9Rytw)
> 
> Context: used the gui, first prompt went through fine, second prompt gave this error:
> 
> ```
> \CASALIOY\venv\Lib\site-packages\llama_cpp\llama_cpp.py", line 335, in llama_eval
>     return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: exception: integer divide by zero
> ```

What was your prompt?

**Comment by alxspiker** [comment]
I was able to ask 3 questions and got a `GGML_ASSERT: C:\Users\Haley The Retard\AppData\Local\Temp\pip-install-m9k6bx9s\llama-cpp-python_e02ecdc8e7e1464e99540ce48153ff94\vendor\llama.cpp\ggml.c:5758: ggml_can_mul_mat(a, b)` with an exit.

**Comment by alxspiker** [comment]
Ah, got your issue:
```
2023-05-14 04:52:09.415 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Haley The Retard\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Haley The Retard\Documents\GitHub\CASALIOY\gui.py", line 90, in <module>
    st.form_submit_button('SUBMIT', on_click=generate_response(st.session_state.input), disabled=st.session_state.running)
  File "C:\Users\Haley The Retard\Documents\GitHub\CASALIOY\gui.py", line 82, in generate_response
  File "C:\Users\Haley The Retard\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_cpp\llama.py", line 564, in embed
    return list(map(float, self.create_embedding(input)["data"][0]["embedding"]))
  File "C:\Users\Haley The Retard\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_cpp\llama.py", line 530, in create_embedding
    self.eval(tokens)
  File "C:\Users\Haley The Retard\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_cpp\llama.py", line 243, in eval
    return_code = llama_cpp.llama_eval(
  File "C:\Users\Haley The Retard\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_cpp\llama_cpp.py", line 335, in llama_eval
    return _lib.llama_eval(ctx, tokens, n_tokens, n_past, n_threads)
OSError: exception: integer divide by zero
```

**Comment by su77ungr** [comment]
Try adding n_batch size as 0.5*n_ctx 

Also we should include the mlock RAM force feature. Runs stable on my side which is very weird

**Comment by hippalectryon-0** [comment]
> What this your prompt that broke it? What documents are in the vector store ?

It was simply `Tell me about shor's algorithm`

**Comment by alxspiker** [comment]
Might have a fix for GUI, I should have initialized the qa_system the same as we are in startLLM

**Comment by su77ungr** [comment]
Did the same test with Shor. Works fine when using n_batch for some reason

**Comment by alxspiker** [comment]
> Did the same test with Shor. Works fine when using n_batch for some reason

Curious, whats your method behind 0.5*n_ctx?

**Comment by alxspiker** [comment]
The steamlit session states are weird to me...

**Comment by su77ungr** [comment]
I was running into error blocks without additional arguments every single time. We should add them to list of on-the-fly change list within the GUI.

**Comment by alxspiker** [comment]
Ill add that change into this version of the GUI

**Comment by su77ungr** [comment]
Also are you running vic7 as the embeddings model?

**Comment by alxspiker** [comment]
No, I am using a single alpaca7b model to do both the embedding and the llm. Have had 0 issues.

**Comment by alxspiker** [comment]
#29 Should fix this!

**Comment by alxspiker** [comment]
@hippalectryon-0 Could you humour me and try with the latest update? I haven't got this error is a while.

**Comment by alxspiker** [comment]
# Problem Identified
Issue is caused by the GUI calling the qa_system while it is already running. Trying to rule out any possible way of it happening.

**Comment by hippalectryon-0** [comment]
> @hippalectryon-0 Could you humour me and try with the latest update? I haven't got this error is a while.

As soon as I get around #30  ^^

**Comment by hippalectryon-0** [comment]
Seems fine so far :)

I opened #40 in the meantime

**Comment by hippalectryon-0** [comment]
Never got this again while refactoring the gui #58 , closing
