### ISSUE TITLE
New convert.py creating massive files ?

### ISSUE THREAD

**Issue by hippalectryon-0** [su77ungr/CASALIOY#34]
Using the "old" convert.py (https://raw.githubusercontent.com/ggerganov/llama.cpp/master/convert.py):
`ggml-model-q4_0.bin` (4Gb) -> `new.bin` (4Gb), takes a few seconds

Using the "new" convert.py (the one in main):
`ggml-model-q4_0.bin` (4Gb) -> `modelsnew.bin` (26Gb !!!), takes a few minutes

What's going on ? ^^

**Comment by su77ungr** [comment]
Also this might be caused by a newer LlamaCpp unit. Get back to the old version until fixed.

**Comment by hippalectryon-0** [comment]
Found the culprit @alxspiker  :P

https://github.com/su77ungr/CASALIOY/blob/6eed358bbf585216853a92506c21ec8bb63331ca/convert.py#L1178

i'm not sure why we hardcoded "f32" but i think it should be `None`.

i'll open a PR soon.

**Comment by alxspiker** [comment]
> Found the culprit @alxspiker :P
> 
> https://github.com/su77ungr/CASALIOY/blob/6eed358bbf585216853a92506c21ec8bb63331ca/convert.py#L1178
> 
> i'm not sure why we hardcoded "f32" but i think it should be `None`.
> 
> i'll open a PR soon.

Honestly just took an existing convert file and just change some things. Don't know much about models in general. I just know how to load and use the llama7b model.
