### ISSUE TITLE
AttributeError: module 'startLLM' has no attribute 'qa_system'

### ISSUE THREAD

**Issue by neeewwww** [su77ungr/CASALIOY#49]
Getting this error when running the GUI:

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.15.9:8501

Input:
Input:
Input:Hello?
Initializing...
llama.cpp: loading model from models/ggml-vic7b-q5_1.bin
llama_model_load_internal: format     = ggjt v2 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1024
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  72.75 KB
llama_model_load_internal: mem required  = 6612.59 MB (+ 1026.00 MB per state)
....................................................................................................
llama_init_from_file: kv self size  =  512.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from models/ggml-vic7b-q5_1.bin
llama_model_load_internal: format     = ggjt v2 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1024
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 9 (mostly Q5_1)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  72.75 KB
llama_model_load_internal: mem required  = 6612.59 MB (+ 1026.00 MB per state)
....................................................................................................
llama_init_from_file: kv self size  =  512.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
2023-05-15 10:57:13.219 Uncaught app exception
Traceback (most recent call last):
  File "D:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "D:\120hz\CASALIOY\gui.py", line 119, in <module>
    on_click=generate_response(st.session_state.input),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\120hz\CASALIOY\gui.py", line 105, in generate_response
    response = startLLM.qa_system(st.session_state.input)
               ^^^^^^^^^^^^^^^^^^
AttributeError: module 'startLLM' has no attribute 'qa_system'

**Comment by hippalectryon-0** [comment]
I'm on it. Just waiting for #50 to be merged first.

**Comment by imSrbh** [comment]
@su77ungr 
Gui has an issue with the latest pull too...

    startLLM.initialize_qa_system()
AttributeError: module 'startLLM' has no attribute 'initialize_qa_system'

**Comment by su77ungr** [comment]
Docker or running the main branch? Docker has some delay. In case of main i'm investigating.

**Comment by imSrbh** [comment]
Ohh Okay
I was working with the main branch.

**Comment by neeewwww** [comment]
Main branch, also.

**Comment by hippalectryon-0** [comment]
Yeah I know, it's alreay fixed, I'm just waiting to finish refactoring the gui script before the PR.
