### ISSUE TITLE
errors when run ingest.py

### ISSUE THREAD

**Issue by jcl2023** [su77ungr/CASALIOY#52]
Any idea why this happens when I run python ingest.py -y.
I need to modify replace with if_elif_else because python version. IT will be nice to avoid using "match" for older python version

Traceback (most recent call last):
  File "/home/test/2TB/GITS/CASALIOY/ingest.py", line 24, in <module>
    from load_env import chunk_overlap, chunk_size, documents_directory, get_embedding_model, persist_directory
  File "/home/test/2TB/GITS/CASALIOY/load_env.py", line 33, in <module>
    def get_embedding_model() -> tuple[HuggingFaceEmbeddings, Callable] | tuple[LlamaCppEmbeddings, Callable]:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'

**Comment by su77ungr** [comment]
what version of python are you running?

**Comment by jcl2023** [comment]
My python version:

python3.9

**Comment by su77ungr** [comment]
switch code in line 35 [load.env]()

```python
from typing import Callable, Union

def get_embedding_model() -> Union[tuple[HuggingFaceEmbeddings, Callable], tuple[LlamaCppEmbeddings, Callable]]:

```

**Comment by hippalectryon-0** [comment]
I suggest against removing match statements to support older python versions, there's really no reason to support python 3.9, even if you're running on a system where you can't install 3.10 (already ~1.5 years old!) you can use the dockerfile.
