### ISSUE TITLE
Error in ingest

### ISSUE THREAD

**Issue by lix2coder** [su77ungr/CASALIOY#59]
I just test the embedding function under directory of models

Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from langchain.embeddings import HuggingFaceEmbeddings, LlamaCppEmbeddings
>>> LlamaCppEmbeddings(model_path='./ggml-model-q4_0.bin', n_ctx=1024)
llama.cpp: loading model from ./ggml-model-q4_0.bin
非法指令 (核心已转储)

**Comment by hippalectryon-0** [comment]
非法指令 (核心已转储) = core dumped.

1) are you using the GPU version ?
2) Can you retry with python 3.10 ?

**Comment by su77ungr** [comment]
@lix2coder since the codebase has been restructured lately; the switch for the sentence-transformer should fix this issue. Ping me if you are still having problems.
