### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by ShadowMikado** [su77ungr/CASALIOY#7]
Hi, I test ingest.py, but I got this error: 
```
loader = TextLoader(os.path.join(root, file), encoding="utf8")
UnboundLocalError: local variable 'root' referenced before assignment
```

**Comment by alxspiker** [comment]
Shouldn't be, does your code look like this? 
<img width="856" alt="image" src="https://github.com/su77ungr/CASALIOY/assets/7357054/c8743863-fbf9-4532-aef5-db58df6c8268">

**Comment by alxspiker** [comment]
Found the issue, delete this line, just noticed it, ill add a PR
<img width="591" alt="image" src="https://github.com/su77ungr/CASALIOY/assets/7357054/043da141-b129-423f-a652-ec5ae1be14ea">

**Comment by su77ungr** [comment]
Jap. Changed it. We should a test for the repo. @ShadowMikado should be working now.

**Comment by alxspiker** [comment]
Looks like I was beat to it! :D
