### ISSUE TITLE
Docker error on windows

### ISSUE THREAD

**Issue by jalle007** [su77ungr/CASALIOY#74]
docker run -it su77ungr/casalioy:stable /bin/bash

docker: Error response from daemon: Bad response from Docker engine.
See 'docker run --help'.

**Comment by hippalectryon-0** [comment]
That sounds like a docker error rather than a project-specific error, can you run other docker containers fine ?

**Comment by su77ungr** [comment]
you have to install dpcker desktop and inside the gui check the box for you wsl. otherwise wsl won't run docker as a system service
