### ISSUE TITLE
UnboundLocalError:

### ISSUE THREAD

**Issue by anonimo28** [su77ungr/CASALIOY#9]
UnboundLocalError: cannot access local variable 'loader' where it is not associated with a value

**Comment by su77ungr** [comment]
Git missed the fix. Now pull and it should work. 
[see](https://github.com/su77ungr/CASALIOY/commit/b2fa87f9e912236b8216312e6e9146a6cec3cfd8)

**Comment by anonimo28** [comment]
I still have this same error-
Traceback (most recent call last):
  File "/Users/yenielfeliciano/Downloads/CASALIOY/ingerir.py", line 42, in <module>
    main(sources_directory, cleandb)
  File "/Users/yenielfeliciano/Downloads/CASALIOY/ingerir.py", line 30, in main
    documents = loader.load()
                ^^^^^^
UnboundLocalError: cannot access local variable 'loader' where it is not associated with a value

**Comment by su77ungr** [comment]
make sure your running ```python3 ingest.py <your_directory>/ y```

I tested it on several machines. Also make sure your requirements file is run.

**Comment by su77ungr** [comment]
@anonimo28 check out latest release.
